### ISSUE TITLE
ROS topic for yumipy

### ISSUE THREAD

**Issue by lz89** [BerkeleyAutomation/yumipy#11]
Hi,

I wonder if there is a ROS topic interface for Yumi control.
Do I need to write my own wrapper for this?
What I want is a set of ROS topics so that I can control the robot in other node (even with roscpp).

Thanks

**Comment by 01halibut** [comment]
The ROS integration for yumipy mostly just uses ROS as a network layer and requires yumipy to be imported in the client node, since it communicates by dumping commands and pose specifications to python pickles.

If you want to control the Yumi over ROS from roscpp then the ROS functionality in Yumipy won't be too helpful.

**Comment by lz89** [comment]
Hi,

So if I want to control Yumi ROS from roscpp the recommended way is this [repo](https://github.com/OrebroUniversity/yumi)?

What does the yumipy service provide in terms of controlling the Yumi?

Thanks!

**Comment by 01halibut** [comment]
In case you're still looking for an answer:

I don't really know what the best way to control Yumi from roscpp is, that repo looks like it should work though.
Yumipy service is just for the Yumi to be controllable over the network from another computer running the same software package.
