### ISSUE TITLE
RAPID server setups for yumipy

### ISSUE THREAD

**Issue by neubotech** [BerkeleyAutomation/yumipy#4]
Hi Jacky,

I'm wondering if there is a general instruction for the RAPID server setups for yumi through robot studio.  

We cannot perform the backup/restore procedure on different YiMi robots.

Thanks!

Nan

**Comment by jacky-liang** [comment]
We'll include these manual instructions in the installation documentation in the future. Although if you can figure out how to restore the backup that's the best way of setting up the server.

Here's the instruction to manually load the modules in RobotStudio. The big idea is we want the SERVER_{} modules to be on Normal tasks and the logger modules to be on Semistatic tasks.

1. Create appropriate tasks. See the following screenshot Controller tab > Configuration Editor > Controller > Tasks: ![tasks](http://i.imgur.com/t0FPaWA.png "Tasks")
*please ignore MotionSupL
*please set all semistatic tasks in the screenshot to normal for now. see more details at the bottom.
2. Restart the robot. (You need to restart the robot if you make changes to tasks)
3. Load the modules in yumipy/RAPID into their corresponding tasks. You do this by:
   1. Set the robot in Manual Mode
   2. Gain write access in RobotStudio
   3. Right click on a specific task under RAPID > {task name}
   4. Click Load Module and select the corresponding .mod file: ![Load Module](http://i.imgur.com/6dHNGu9.png "Load Module")

| task name                            | module file                         |
|--------------------------------------|-------------------------------------|
| T_ROB_L                              | SERVER_LEFT.mod                     |
| T_ROB_R                              | SERVER_RIGHT.mod                    |
| Shared                               | Constants.mod                       |
| {Joints, Poses, Torques}Logger{L, R} | {joints, poses, torques}_logger.mod |

    *Note that the logger modules are identical for left and right versions, except for the name of the port variable which appears twice in each script. Right now those variables are for the left versions (e.g. PORT_JOINTS_LOGGER_L). Make sure you change those to _R for the "right" tasks.

4. Set PP to Main and run all tasks. Verify YuMiRobot and YuMiSubscriber works.
5. Set all the semistatic tasks in the screenshot to semistatic.
6. Restart robot
 
Notes about types of tasks:

* Normal tasks are tasks you can start and stop with the FlexPendant and RobotStudio
* Semistatic tasks are always running and cannot be stopped. When the robot restarts a semistatic task will always start the program in its module at the main() function.
* Static tasks are tasks that are also always running. But when the robot restarts a static task will resume the program in its module at whichever line the program was on when the robot turned off.

You cannot modify the program in the modules of semistatic and static tasks. In order to change those programs you must first change the task type to normal, restart the robot, make your modifications, change the task type, then restart the robot again.

Notes about the server files:

SERVER_LEFT and SERVER_RIGHT provide all the functionalities you need to run the python class YuMiRobot. All the other modules and tasks are there to provide support for YuMiSubcriber.
